FROM php:7.0-apache
LABEL maintainer Daniel Palumbo <daniel.palumbo@heig-vd.ch>
LABEL maintainer Christopher Meier <christopher.meier@heig-vd.ch>


# We use the image default apache configuration.

# We copy the web site files.
COPY ./httpdoc/ /var/www/html

