FROM node:4.4 
LABEL maintainer Daniel Palumbo <daniel.palumbo@heig-vd.ch>
LABEL maintainer Christopher Meier <christopher.meier@heig-vd.ch>

COPY ./src /opt/app

EXPOSE 3000

CMD ["node", "/opt/app/index.js"]
