FROM traefik:latest
LABEL maintainer Daniel Palumbo <daniel.palumbo@heig-vd.ch>
LABEL maintainer Christopher Meier <christopher.meier@heig-vd.ch>

# We copy the traefik configuration file.
COPY ./traefik.toml /etc/traefik/traefik.toml

